### ISSUE TITLE
PS1 games on RPi2

### ISSUE THREAD

**Issue by jbtrystram** [zach-morris/plugin.program.iarl#15]
Hi,

I can't download any PS1 roms through IARL.. I've been searching a bit and understand that 7z support is a bit complicated in OpenElec (using on an RPi2). When the rom is downloaded it says "error, see the log". But I can't find where the logfile is ?

I wanted to understand where the problem was :
I tried to download an image elswhere, uncompress the 7z, then found out that bin.ecm files weren't supported, uncompressed the ecm file into a bin file... then retroarch scan it, but still says "no item" in the directory. 

So I don't know what's the real issue here !?

**Comment by zach-morris** [comment]
The logfile is the kodi log.
See here:  http://kodi.wiki/view/Log_file/Advanced

Without a log, I'm only guessing, but it's most likely a permissions issue.  7zip is probably not able to be executed because your not the root user.

See step 6 in the [basic setup instructions](https://github.com/zach-morris/plugin.program.iarl/wiki/1.--Setup) on chmod.

**Comment by pcross616** [comment]
had the same issue here on a windows box.  Looks like its the links..  I modified and printed out the dict object to get the URL and non of the PS1 urls seem to work, site removed them.

[List of ROMs](https://archive.org/download/psx_redump_usa_20141221)

Click on one and an error is returned.  That is the content  of the 7z file when it is downloaded thats why it will not un-compress.

Do you have a new set of links or a backup of those roms.

`00:24:55 T:7588   ERROR: IARL:  PETE!! There was an error converting the 7z files for {'rom_plot': 'Metal Gear Solid demanded a lot from its players. For one, we had to learn to stop mashing on our controllers like mindless sitcom actors for two seconds and simply watch a video game. When we did have control, there was a whole lot of careful sneaking and quiet killing. Go in guns blazing (well, as close as you could get to guns blazing in MGS) and you were met with swift, crushing defeat. Why did we ever put up with it?[CR][CR]Because not only did MGS deliver a thrilling interactive experience, it was the next evolution in gaming. Its movie-like cutscenes and meticulously designed, stealth-centric levels were evidence of a production value not normally seen in a video game. Konami and Kojima tried for a lot here, and pulled it all off brilliantly.', 'rom_date': None, 'rom_emu_command': None, 'rom_trailer': 'plugin://plugin.video.youtube/play/?video_id=lt2K45vwTM4', 'rom_nplayers': '1', 'rom_snapshots': ['http://thegamesdb.net/banners/screenshots/196-1.jpg', 'http://thegamesdb.net/banners/screenshots/196-2.jpg', 'http://thegamesdb.net/banners/screenshots/196-3.jpg', 'http://www.mobygames.com/images/shots/l/52052-metal-gear-solid-playstation-screenshot-main-menu.jpg', 'http://www.mobygames.com/images/shots/l/52055-metal-gear-solid-playstation-screenshot-when-in-a-narrow-space.jpg', 'http://www.mobygames.com/images/shots/l/52056-metal-gear-solid-playstation-screenshot-a-standard-safe-way.jpg', 'http://www.mobygames.com/images/shots/l/52057-metal-gear-solid-playstation-screenshot-as-the-game-starts.jpg', 'http://www.mobygames.com/images/shots/l/52058-metal-gear-solid-playstation-screenshot-nice-effects-such-as.jpg', 'http://www.mobygames.com/images/shots/l/52059-metal-gear-solid-playstation-screenshot-this-game-requirea.jpg', 'http://www.mobygames.com/images/shots/l/52060-metal-gear-solid-playstation-screenshot-right-icon-holds-the.jpg'], 'rom_thumbnail': 'http://thegamesdb.net/banners/boxart/original/front/196-2.jpg', 'rom_name': '2.  Metal Gear Solid', 'rom_label': '2.  Metal Gear Solid', 'rom_esrb': 'M - Mature', 'rom_boxarts': ['http://thegamesdb.net/banners/boxart/original/front/196-2.jpg', 'http://thegamesdb.net/banners/boxart/original/back/196-1.jpg', 'http://i.imgur.com/VqVeiR7.png', 'http://i.imgur.com/LQzuJmN.png', 'http://www.mobygames.com/images/covers/l/33479-metal-gear-solid-playstation-media.jpg', 'http://www.mobygames.com/images/covers/l/33480-metal-gear-solid-playstation-media.jpg', 'http://www.mobygames.com/images/covers/l/272476-metal-gear-solid-playstation-media.jpg', 'http://www.mobygames.com/images/covers/l/272477-metal-gear-solid-playstation-media.jpg', 'http://www.mobygames.com/images/covers/l/39732-metal-gear-solid-playstation-media.jpg', 'http://www.mobygames.com/images/covers/l/39733-metal-gear-solid-playstation-media.jpg'], 'rom_save_supporting_filenames': [None], 'rom_supporting_filenames': [None], 'rom_title': '2.  Metal Gear Solid', 'rom_filenames': ['https://archive.org/download/psx_redump_usa_20141221/Metal Gear Solid (USA) (Disc 1) (v1.1).7z', 'https://archive.org/download/psx_redump_usa_20141221/Metal Gear Solid (USA) (Disc 2) (v1.1).7z'], 'rom_size': [433027136, 395831687], 'rom_save_filenames': ['C:\\Users\\mediacenter\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.program.iarl\\temp_iarl\\Metal Gear Solid (USA) (Disc 1) (v1.1).7z', 'C:\\Users\\mediacenter\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.program.iarl\\temp_iarl\\Metal Gear Solid (USA) (Disc 2) (v1.1).7z'], 'rom_perspective': '1st-Person', 'rom_logos': ['http://thegamesdb.net/banners/clearlogo/196.png', None, None, None, None, None, None, None, None, None], 'rom_studio': 'Konami of America, Inc.', 'rom_tag': None, 'rom_banners': ['http://i.imgur.com/dgczcqZ.png', None, None, None, None, None, None, None, None, None], 'rom_fanarts': ['http://thegamesdb.net/banners/fanart/original/196-1.jpg', 'http://thegamesdb.net/banners/fanart/original/196-2.jpg', 'http://thegamesdb.net/banners/fanart/original/196-3.jpg', 'http://thegamesdb.net/banners/fanart/original/196-4.jpg', 'http://thegamesdb.net/banners/fanart/original/196-5.jpg', 'http://thegamesdb.net/banners/fanart/original/196-6.jpg', 'http://thegamesdb.net/banners/fanart/original/196-7.jpg', 'http://thegamesdb.net/banners/fanart/original/196-8.jpg', None, None], 'rom_year': '1999', 'rom_rating': '4.0', 'rom_icon': 'http://thegamesdb.net/banners/boxart/original/front/196-2.jpg', 'rom_genre': 'Action'}
00:24:55 T:7588   ERROR: I AM HERE: {'rom_save_supporting_filenames': [], 'overwrite_existing_files': False, 'rom_converted_supporting_filenames_success': [], 'rom_supporting_filenames': [], 'launch_filename': None, 'rom_save_supporting_filenames_exist': [], 'overall_conversion_success': False, 'rom_save_filenames_exist': [True, True], 'rom_save_filenames_success': [True, True], 'rom_converted_supporting_filenames': [], 'rom_save_filenames': ['C:\\Users\\mediacenter\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.program.iarl\\temp_iarl\\Metal Gear Solid (USA) (Disc 1) (v1.1).7z', 'C:\\Users\\mediacenter\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.program.iarl\\temp_iarl\\Metal Gear Solid (USA) (Disc 2) (v1.1).7z'], 'matching_rom_save_filenames': [None, None], 'matching_rom_save_supporting_filenames': [], 'rom_save_supporting_filenames_success': [], 'rom_converted_filenames': [None], 'overall_download_success': True, 'rom_converted_filenames_success': [False]}
00:24:55 T:7588   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: coercing to Unicode: need string or buffer, NoneType found
                                            Traceback (most recent call last):
                                              File "C:\Users\mediacenter\AppData\Roaming\Kodi\addons\plugin.program.iarl\addon.py", line 1584, in onClick
                                                download_and_launch_rom(self,iarl_data)
                                              File "C:\Users\mediacenter\AppData\Roaming\Kodi\addons\plugin.program.iarl\addon.py", line 1371, in download_and_launch_rom
                                                current_external_command = replace_external_launch_variables(iarl_data) #Function replaces command line variables
                                              File "C:\Users\mediacenter\AppData\Roaming\Kodi\addons\plugin.program.iarl\resources\lib\util.py", line 818, in replace_external_launch_variables
                                                command_out = command_out.replace('%ROM_PATH%',iarl_data['current_save_data']['launch_filename']) #Replace ROM filepath
                                            TypeError: coercing to Unicode: need string or buffer, NoneType found
                                            -->End of Python script error report<--
`

**Comment by jbtrystram** [comment]
@zach-morris thanks for the tip ! I tried to chmod the binaries, with no luck.
here is the relevant log : 
```
21:40:28 1745.750244 T:1589638048   ERROR: IARL:  There was an error converting the 7z files for 4.  Tony H
awk's Pro Skater 2
21:40:28 1745.752441 T:1589638048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/scr
ipt returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: coercing to Unicode: need string or buffer, Non
eType found
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.program.iarl/addon.py", li
ne 1583, in onClick
                                                download_and_launch_rom(self,iarl_data)
                                              File "/storage/.kodi/addons/plugin.program.iarl/addon.py", li
ne 1370, in download_and_launch_rom
                                                current_external_command = replace_external_launch_variable
s(iarl_data) #Function replaces command line variables
                                              File "/storage/.kodi/addons/plugin.program.iarl/resources/lib
/util.py", line 818, in replace_external_launch_variables
                                                command_out = command_out.replace('%ROM_PATH%',iarl_data['c
urrent_save_data']['launch_filename']) #Replace ROM filepath
                                            TypeError: coercing to Unicode: need string or buffer, NoneType
 found
                                            -->End of Python script error report<--
```

**Comment by zach-morris** [comment]
@pcross616 
The debug log will also print out the URL if your looking for it.  However, see setup info at the bottom of the page [here](https://github.com/zach-morris/plugin.program.iarl/wiki/1.--Setup).  Archive.org requires login info for certain flagged archives.

**Comment by pcross616** [comment]
@zach-morris I have an Archive account (though I didn't see a way to add that to the add-on setup) and when I use the archive directly via a web browser it doesn't work ether so the roms don't exist anymore or have been removed by the poster.

**Comment by pcross616** [comment]
Ok just ran a few more tests, it does look like its related to being logged in.  You must have an account for the PS1 roms to work.

**Comment by zach-morris** [comment]
I've added some code to show a message if this is the case.  I'll consider this fixed.
