### ISSUE TITLE
Can't download to external SD card

### ISSUE THREAD

**Issue by Baldyshugga** [zach-morris/plugin.program.iarl#28]
When I choose to set a custom download location I pick the external sd card and it shows the card content and accepts it, but when trying to download a game the download fails like it can't access the card or didn't have permission. Any fix for this?

**Comment by zach-morris** [comment]
Hmm... I dunno.  This would mean Kodi doesn't have permissions to write to the card.  Do you have root / admin access on the machine?  I assume you'd need to make the SD card writeable using chmod or something like it.

**Comment by Baldyshugga** [comment]
No I don't have root access. I'm on a Shield K1. I'll try to get a Kodi debug l log.

**Comment by Baldyshugga** [comment]
[kodi.log.zip](https://github.com/zach-morris/plugin.program.iarl/files/870140/kodi.log.zip)
Try this log.

**Comment by zach-morris** [comment]
Yeah, the error shows
`IOError: (13, Permission denied`

Which is a python error, which is part of Kodi and not the addon directly.  Some quick googling provides a [possible solution](http://www.aftvnews.com/how-to-fix-usb-drive-or-microsd-card-file-permision-issues-caused-by-fire-os-5-on-the-fire-tv/).

**Comment by Baldyshugga** [comment]
So basically I need root to fix this problem. Thanks for the help anyway.

**Comment by zach-morris** [comment]
I think the workaround is to create a folder on the SDCard:
/storage/sdcard/Android/data/org.xbmc.kodi/

where sdcard is the name or path to your SD card in Android.  According to the info on that site Android apps do not need permissions if the folder name matches the app name.

In theory then you could make subfolders like:
/storage/sdcard/Android/data/org.xbmc.kodi/PS1
/storage/sdcard/Android/data/org.xbmc.kodi/NES
etc

In any case, this is a limitation of Kodi rather than IARL.  Nothing I can do about permission restrictions.
