### ISSUE TITLE
Mame and arcade games external launch command not defined RPI

### ISSUE THREAD

**Issue by pablinho1023** [zach-morris/plugin.program.iarl#45]
Hi zach, first thank you for such awesome addon, its just incredible i been using it for almost a year with openelec and its great.

The only problem is that i cant play mame or arcade games, when i try to launch the game the "external launch command" problem always appear and i cant seem to solve it, i already read all the information in here but still cant get rid of it, could you help me?
im using openelec with a raspberry pi 3, thank you so much!

**Comment by zach-morris** [comment]
For MAME games on the RPi, you'll likely want to be using the MAME2003 lists, simply because the RPi isn't powerful enough to run any version of MAME newer than that.  See [here](https://github.com/retropie/retropie-setup/wiki/MAME#lr-mame2003-mame-2003) for more info on the different MAME versions on RPi.

Make sure you:
Have the MAME2003 libretro core on your RPi (assuming you're using GameStarter, it should already be included)
Highlight the MAME 2003 list in IARL (if it's not shown, then go to advanced settings and "unhide all archives").
Select Update Launcher, set to External
Select Update external launch command, set to 'RetroArch MAME 2003 (Arcade 0.78)'

Thats all that should be required.

**Comment by pablinho1023** [comment]
Thanks for the fast reply, i already did that, in fact i try to play kof 98, i can do all the steps but when i get to Select Update external launch command, the only options that appear are Manually entered command line or None, theres no RetroArch MAME 2003 (Arcade 0.78), any idea why is this?

**Comment by zach-morris** [comment]
If there's nothing else listed, then the addon doesn't know what your "System Type" is.  In the addon settings, external launchers tab, set your system type.  This is gonna depend on your setup.  Are you using Gamestarter?  If so, select Gamestarter.

**Comment by pablinho1023** [comment]
yes it is, the system is, Openelec rpi (gamestarter)

**Comment by pablinho1023** [comment]
ohhh yeah it now changed and appeared the options!! Awesome man!! Let me check if it works now!

**Comment by pablinho1023** [comment]
its working!!!!!!!!! Really really thank you!

**Comment by zach-morris** [comment]
Good deal, semi-realtime troubleshooting ;-)
