### ISSUE TITLE
Controller input not working in retroarch

### ISSUE THREAD

**Issue by ragesoss** [zach-morris/plugin.program.iarl#59]
This is a great project!

I'm stuck getting it working on my system, and I'm not sure how to proceed. I'm running it on Debian Stretch.

I got IARL installed successfully on my system, and after some trial and error — I had to install retroarch and fceux via apt, and then add .config/retroarch to the IARL settings — it now will launch a NES rom. However, controller input is not registering in retroarch.

I installed 'kodi-peripheral-joystick', which made the controller work within the Kodi UI. But the Kodi gamepad config doesn't seem to carry over to retroarch, and retroarch seems to be getting no input at all from the controller.

I also tried using retropie-setup to install emulationstation, and I get the same issue when I launch it on top of a Kodi session: no controller input. The controller works in emulationstation if a I launch it from a Gnome or Plasma session.

Any ideas for configuring controllers to work both in Kodi and with emulators launched by IARL?

**Comment by zach-morris** [comment]
I've never used this setup..  But, once the game launches, IARL and Kodi are totally out of the loop.  They're completely separate applications.  Make sure control works in Retroarch standalone (without launching a game with IARL).  If you get that working, then I'd make sure the following:
1)  The config file Retroarch has defined in settings is the same config file IARL is pointing to
2)  If the first is true, then maybe Kodi is 'stealing' control of the controller.  You could try enabling 'close Kodi before launching'  which will run a shell script to exit Kodi, then launch the game, then restart Kodi after you exit Retroarch
3)  If that still doesn't work.  Gamestarter addon may work for your system since it's built for x86 generic OS's.  No guarantees though since I've never used that OS.  You could try installing Gamestarter.  See install info [here](https://github.com/zach-morris/plugin.program.iarl/wiki/0.--Installation#2-retroarch).

**Comment by ragesoss** [comment]
Thanks! It looks like it was (2). I enabled the 'close before launching' option, and now the controller works. :-)
